module.exports = {
    DYNAMIC_LIGHT_KIND: {
        BEHAVIOR_DYNAMIC_LIGHT: "BEHAVIOR_DYNAMIC_LIGHT",
        DYNAMIC_DIR_CHARACTER_LIGHT: "DYNAMIC_DIR_CHARACTER_LIGHT",
        DYNAMIC_LIGHT: "DYNAMIC_LIGHT",
    }
}