module.exports = {
    ACTION: {
        CREATE: "CREATE",
        CREATE_FORCE: "CREATE_FORCE",
        CREATE_IF_NOT_EXIST: "CREATE_IF_NOT_EXIST",
        REMOVE: "REMOVE",
        REMOVE_IF_EXIST: "REMOVE_IF_EXIST",
        UPDATE: "UPDATE"
    },
    GROUP_NAME: {
        OVERRIDE_OBJECT: "OVERRIDE_OBJECT", // {...}
        OVERRIDE_OBJECT_WITH_LIST: "OVERRIDE_OBJECT_WITH_LIST", // {"list": [{...}]
        OBJECT_WITH_LIST_ACTION_NAME: "OBJECT_WITH_LIST_ACTION_NAME", // {"list": [{"action: "...", name": "..."}]
        OBJECT_WITH_LIST_ACTION_TARGET: "OBJECT_WITH_LIST_ACTION_TARGET", // {"list": [{"action: "...", "target": "..."}]
        OBJECT_WITH_LIST_ACTION_TARGET_ID: "OBJECT_WITH_LIST_ACTION_TARGET_ID", // {"list": [{"action: "...", "target": "...", "id": "..."}]
        OBJECT_WITH_LIST_ACTION_ID: "OBJECT_WITH_LIST_ACTION_ID", // {"list": [{"action: "...", "id": "..."}]
        OBJECT_WITH_OPTIONAL_LIST_ACTION_ID: "OBJECT_WITH_OPTIONAL_LIST_ACTION_ID", // {"list": [{"action: "...", "id": "..."}] / {}
        OBJECT_WITH_LIST_ACTION_ID_NAME: "OBJECT_WITH_LIST_ACTION_ID_NAME", // {"list": [{"action: "...", "id": "...", "name": "..."}]
        DEFINITIONS_OBJECT: "DEFINITIONS_OBJECT", // {"...": "...", "...": "..."}
        DEFINITIONS_OBJECT_STORE: "DEFINITIONS_OBJECT_STORE", // {"...": "...", "...": "..."}
        INSTANT_CALL_OBJECT: "INSTANT_CALL_OBJECT" // {...}
    },
    TYPE: {
        VAL_OR_GET_RANDOM_ELEMENTS: "VAL_OR_GET_RANDOM_ELEMENTS",
        BOOL: "BOOL",
        INT: "INT",
        INT_OR_BOOL: "INT_OR_BOOL",
        INT_OR_GET_CHARACTER_DATA: "INT_OR_GET_CHARACTER_DATA",
        INT_OR_GET_RANDOM_ELEMENTS: "INT_OR_GET_RANDOM_ELEMENTS",
        INT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS: "INT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS",
        FLOAT: "FLOAT",
        FLOAT_OR_GET_RANDOM_ELEMENTS: "FLOAT_OR_GET_RANDOM_ELEMENTS",
        FLOAT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS: "FLOAT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS",
        FLOAT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS_OR_MASTER: "FLOAT_OR_GET_CHARACTER_DATA_OR_GET_RANDOM_ELEMENTS_OR_MASTER",
        ARRAY: "ARRAY",
        OBJECT: "OBJECT",
        RGB_COLOR: "RGB_COLOR",
        RGBA_COLOR: "RGBA_COLOR",
        RGB_OR_RGBA_COLOR: "RGB_OR_RGBA_COLOR",
        RGB_OR_RGBA_COLOR_GET_RANDOM_ELEMENTS: "RGB_OR_RGBA_COLOR_GET_RANDOM_ELEMENTS",

        TARGET: "TARGET",

    },
    TARGET_KIND: {
        THIS_NPC_INSTANCE: "THIS_NPC_INSTANCE"
    },
    CONFIGURATION_TYPE: {
        NORMAL_SRAJ: "NORMAL_SRAJ",
        NIGHT: "NIGHT",
        WEATHER: "WEATHER",
        SOUND: "SOUND "
    }
};