module.exports = {
    SEND_CHAT_MESSAGE: "SEND_CHAT_MESSAGE",
    SHOW_EQ: "SHOW_EQ",
    INVITE_TO_FRIEND: "INVITE_TO_FRIEND",
    INVITE_TO_ENEMIES: "INVITE_TO_ENEMIES",
    INVITE_TO_PARTY: "INVITE_TO_PARTY",
    SHOW_PROFILE: "SHOW_PROFILE"
}