let o = {
    missionObjective: {
        LootCommonItem: 1,
        LootUniqueItem: 2,
        LootHeroicItem: 3,
        LootLegendaryItem: 4,
        LootArtefactItem: 5,
        DuelWithPlayer: 6,
        LoseDuelWithPlayer: 7,
        KillCommonMonster: 8,
        KillEliteMonster: 9,
        KillElite2Monster: 10,
        KillHeroMonster: 11,
        KillTitanMonster: 12,
        KillMonsterWithIndestructibleLoot: 13,
        KillMonsterWithCritical: 14,
        KillPlayerWithCritical: 15,
        KillPlayer: 16,
        KillPaladin: 17,
        KillMage: 18,
        KillWarrior: 19,
        KillBladeDancer: 20,
        KillHunter: 21,
        KillTracker: 22,
        DealDamage: 23,
        DealPhysicalDamageToPlayer: 24,
        DealPhysicalDamageToNpc: 25,
        DealFireDamageToPlayer: 26,
        DealFireDamageToNpc: 27,
        DealFrostDamageToPlayer: 28,
        DealFrostDamageToNpc: 29,
        DealLightDamageToPlayer: 30,
        DealLightDamageToNpc: 31,
        DealPoisonDamageToPlayer: 32,
        DealPoisonDamageToNpc: 33,
        DealDeepWoundDamageToPlayer: 34,
        DealDeepWoundDamageToNpc: 35,
        HealByItem: 36,
        HealByTalisman: 37,
        HealSelfInBattle: 38,
        HealAllyInBattle: 39,
        ExtractItem: 40,
        ExtractCommonItem: 41,
        ExtractUniqueItem: 42,
        ExtractUpgradedItem: 43,
        ExtractHeroicItem: 44,
        ExtractLegendaryItem: 45,
        ExtractArtefactItem: 46,
        SalvageItem: 47,
        SalvageCommonItem: 48,
        SalvageUniqueItem: 49,
        SalvageUpgradedItem: 50,
        SalvageHeroicItem: 51,
        SalvageLegendaryItem: 52,
        SalvageArtefactItem: 53,
        GainEssencesAmount: 54,
        EnhanceItem: 55,
        EnhanceCommonItem: 56,
        EnhanceUniqueItem: 57,
        EnhanceHeroicItem: 58,
        EnhanceUpgradedItem: 59,
        EnhanceLegendaryItem: 60,
        EnhanceArtefactItem: 61,
        UpgradeItem: 62,
        UpgradeCommonItem: 63,
        UpgradeUniqueItem: 64,
        UpgradeUpgradedItem: 65,
        UpgradeHeroicItem: 66,
        UpgradeLegendaryItem: 67,
        UpgradeArtefactItem: 68,
        ReselectBonusItem: 69,
        BuyAuctionItem: 70,
        SellItemInAuction: 71,
        SellItemInShop: 72,
        GainGoldFromShop: 73,
        SpentGoldInShop: 74,
        SendMail: 75,
        UseBarter: 76,
        UseBless: 77,
        BuyClanBless: 78,
        TradeWithPlayer: 79,
        AddFriend: 80,
        UseEmotion: 81,
        UseEmotionOnPlayer: 82,
        GainExperiencePoints: 83,
        GainHonorPoints: 84,
        LoseHonorPointsInDuelWithPlayer: 85,
        PickUpRenewableItem: 86
    },
    missionObjectiveByKey: {

    }
};

for (let k in o.missionObjective) {
    let val = o.missionObjective[k];
    o.missionObjectiveByKey[val] = k;
}


module.exports = o