module.exports = {
    group: {
        MOVE: 'move',
        FIGHT: 'fight',
        MAP: 'map',
        SOCIAL: 'social',
        OTHER: 'other'
    },
    type: {
        TIP: 'Tip',
        LABEL: 'Label'
    },
    name: {
        showBuildWindow: 'showBuildWindow',
        hotAttackNearMob: 'hotAttackNearMob',
        autofightNearMob: 'autofightNearMob',
        hotAttackNearPlayer: 'hotAttackNearPlayer',
        hotChangeTarget: 'hotChangeTarget',
        hotAutoFight: 'hotAutoFight',
        hotAcceptLoot: 'hotAcceptLoot',
        toggleBattlePanel: 'toggleBattlePanel',
        hotCloseFight: 'hotCloseFight',
        showLog: 'showLog',
        iconglobe: 'iconglobe',
        hotportablemap: 'hotportablemap',
        iconcompass: 'iconcompass',
        goGateway: 'goGateway',
        hotTalkNearMob: 'hotTalkNearMob',
        iconchat: 'iconchat',
        iconclans: 'iconclans',
        iconfriends: 'iconfriends',
        iconparty: 'iconparty',
        quickParty: 'quickParty',
        clanSendMessage: 'clanSendMessage',
        iconconfig: 'iconconfig',
        iconkeyboard: 'iconkeyboard',
        iconWindows: 'iconWindows',
        iconpuzzle: 'iconpuzzle',
        iconconsole: 'iconconsole',
        eqcolumnshow: 'eqcolumnshow',
        showhideStats: 'showhideStats',
        hotAuction: 'hotAuction',
        iconphoto: 'iconphoto',
        iconscroll: 'iconscroll',
        iconskills: 'iconskills',
        iconexit: 'iconexit',
        iconstar: 'iconstar',
        news: 'news',
        matchmaking: 'matchmaking',
        achievements: 'achievements',
        hotTakeGroundItem: 'hotTakeGroundItem',
        world: 'world',
        zoom: 'zoom',

        move_up: 'move_up',
        move_down: 'move_down',
        move_left: 'move_left',
        move_right: 'move_right',
    }
}